// weatherApp_React/src/components/Weather.js
import React from 'react';

const Timestamp = require('react-timestamp');

const Weather = props => (	

<div> 
	<div className="weather-container"> 
{
	props.city && props.country && 
<p className="weather__key">Location:<span className="weather__value">{props.city}, {props.country}</span></p>
}
{
	props.icon && <p className="weather__key__icon"><img src={"http://openweathermap.org/img/w/"+props.icon+".png"}/></p>
}
{
	props.description && <p className="weather__key">Weather Conditions:<span className="weather__value">{props.description}</span></p>
}
{
	props.temperature && <p className="weather__key">Temperature:<span className="weather__value">{props.temperature} &deg;C</span>
	</p>
}
{
	props.temp_min && <p className="weather__key">Coldest:<span className="weather__value">{props.temp_min} &deg;C</span>
	</p>
}
{
	props.temp_max && <p className="weather__key">Hottest:<span className="weather__value">{props.temp_max} &deg;C</span>
	</p>
}
{
	props.sunrise && <p className="weather__key">Sunrise:<span className="weather__value"><Timestamp time={props.sunrise} format="time" /></span>
	</p>
}
{
	props.sunset && <p className="weather__key">Sunset:<span className="weather__value"><Timestamp time={props.sunset} format="time"/></span>
	</p>
}

{
	props.latitude && <p className="weather__key">Latitude:<span className="weather__value">{props.latitude}</span>
	</p>
}
{
	props.longitude && <p className="weather__key">Longitude:<span className="weather__value">{props.longitude}</span>
	</p>
}
{
	props.humidity && <p className="weather__key">Humidity:<span className="weather__value">{props.humidity}</span></p>
}

{
	props.error && <p className="weather__key"><span className="weather__error">{props.error}</span></p>
}
</div>
  </div>
		);
	

export default Weather;

// weatherApp_Vue/src/components/Weather.vue

<template>
 <div class="container" id="weatherinfo">
      
    <div class="col-md-8 form-container">
         <div class="col-md-8">
        
            <input type="text"  v-model="city" placeholder="City">
             <input type="text"  v-model="country" placeholder="Country">
              <button type="submit" v-on:click='getData'>Search</button>
        </div>
        <div >
            <div  >                     
                <p class="weather__key">Selected Location:<span class="weather__value">{{city}}, {{country}}</span></p>
                <p v-html="icon" class="weather__key"><span class="weather__value">{{icon}}</span></p>
                <p class="weather__key">Weather Condition: <span class="weather__value">{{ description }}</span></p>
                <p class="weather__key">Average Temperature :  <span class="weather__value">{{temperature }}</span></p>
                <p  v-html="temp_min" class="weather__key"> <span class="weather__value">{{temp_min }}</span></p>
                <p class="weather__key">Hottest :  <span class="weather__value">{{temp_max }}</span></p>
                <p class="weather__key">Sunrise :  <span class="weather__value">{{sunrise }}</span></p>
                <p class="weather__key">Sunset :  <span class="weather__value">{{sunset }}</span></p>
                <p class="weather__key">Latitude : <span class="weather__value">{{latitude }}</span></p>
                <p class="weather__key"> Longitude: <span class="weather__value">{{longitude}}</span></p>                        
            </div>
        </div>
    </div>
</div>

</template>

<script>

export default {

  data(){
    return{
city:'',
country:'',
description:'',
icon: '',
temperature:'',
temp_min:'',
temp_max:'',
sunrise:'',
sunset:'',
latitude:'',
longitude:''
    }
  },

  methods : {
    getData: function(){
        var self = this;
        axios.get('http://api.openweathermap.org/data/2.5/weather?q='+self.city+','+self.country +'&appid=e72a4b1901da3ae63f2b229a8878f024&units=metric').then(function(response){
            console.log(response); 
            self.city = response.data.main.city;
            self.country = response.data.sys.country; 
            self.description = response.data.weather[0].description;
self.icon = response.data.weather[0].icon; 
self.icon ='<img src="http://openweathermap.org/img/w/'+response.data.weather[0].icon+'.png">' ;
self.temperature = response.data.main.temp;
self.temp_min = response.data.main.temp_min;
self.temp_max = response.data.main.temp_max;
self.sunrise =  response.data.sys.sunrise;
self.sunset = response.data.sys.sunset;
self.latitude = response.data.coord.lat;
self.longitude  = response.data.coord.lon;
    }).catch(function(error){
            self.city = 'Invalid City';
            self.country = 'Invalid Country';
        });
    }
   
}
 
}
</script>

<style>


</style>
